# Generated by Django 6.0 on 2025-12-10 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("order_num", models.IntegerField(db_column="order", default=0)),
                ("description", models.CharField(default="New Chat", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_history",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("HUMAN", "Human"), ("AI", "AI"), ("TOOLS", "Tools")],
                        max_length=10,
                    ),
                ),
                ("order_num", models.IntegerField(db_column="order")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "history",
                    models.ForeignKey(
                        db_column="history_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="chat.chathistory",
                    ),
                ),
            ],
            options={
                "db_table": "chat",
                "ordering": ["order_num"],
            },
        ),
    ]
