# Generated by Django 6.0 on 2025-12-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
